/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EstherVistas;

import EstherModelo.LoginDAO;
import EstherModelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author dani_
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cbNivel = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 270, 40));

        cbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Gerente", "Vendedor" }));
        cbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNivelActionPerformed(evt);
            }
        });
        getContentPane().add(cbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 270, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 230, 300));

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 110, 40));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 510, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNivelActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        LoginDAO modSql= new LoginDAO();
        Usuario mod= new Usuario();
        String us= txtUsuario.getText();
        String pass= new String(txtPass.getPassword());
        if(!txtUsuario.getText().equals("") && !pass.equals("")){
            mod.setNombre(txtUsuario.getText());
            mod.setPass(pass);
            if(cbNivel.getSelectedItem()=="Administrador"){
                if(modSql.loginA(mod)){
                    this.dispose();
                    V_Inicio inicio=new V_Inicio(mod);
                    inicio.setVisible(true);
                    
                
                }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                }
            }else if(cbNivel.getSelectedItem()=="Gerente"){
                if(modSql.loginG(mod)){
                this.dispose();
                V_Inicio inicio=new V_Inicio(mod);
                inicio.setVisible(true);
                
                }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                }
                
            }else if(cbNivel.getSelectedItem()=="Vendedor"){
                if(modSql.loginV(mod)){
                this.dispose();
                V_Inicio inicio=new V_Inicio(mod);
                inicio.setVisible(true);
                
                }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                }
            }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        login v= new login();
        v.setVisible(true);
        v.setLocationRelativeTo(v);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEntrar;
    public javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
