/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.joyeria.vistas;

import Vistas.V_Inventario;
import com.joyeria.Dao.V_productoDao;
import com.joyeria.Dao.V_ventaDao;
import com.joyeria.controller.v_clientecontroller;
import com.joyeria.controller.v_ventacontroller;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dani_
 */
public class V_ventas extends javax.swing.JFrame {
    public static int usuario;
    public static int nivel_usuario;
    public static int sucursal;
    public static int cliente;
    public static int id_venta;
    public static String nombre_completo;
   public int cantidad_piezas;
   public double subtotal;
   public double importe_total;
   public double descuento;
    public String seleccion;
       v_ventacontroller v_controller = new v_ventacontroller();
       V_ventaDao v_ventaDao = new V_ventaDao();
       V_productoDao dao = new V_productoDao();
    
                       
    /**
     * Creates new form V_Ventas
     */
    public V_ventas() throws SQLException  {
        initComponents();
        this.setLocationRelativeTo(null);
        jtbproductos.getTableHeader().setReorderingAllowed(false);
         
     
    }
        public V_ventas(int id_venta) throws SQLException  {
        initComponents();
        this.setLocationRelativeTo(null);
        jtbproductos.getTableHeader().setReorderingAllowed(false);
        datos_Venta();
      
    }
    
     public void datos_Venta() throws SQLException {
        ResultSet rs = v_ventaDao.seleccionar_id(id_venta);
        while (rs.next()) {
            txtno_venta.setText(String.valueOf(rs.getInt(1)));
            txtfecha.setText(String.valueOf(rs.getString(2)));
            txtid_cliente.setText(String.valueOf(rs.getInt(4)));
            txtnombre_cliente.setText(String.valueOf(rs.getString(5)));
            
        }
    }
      public void contar_piezas() {
        cantidad_piezas = v_controller.contar_venta(id_venta);
        txtpiezas.setText(String.valueOf(cantidad_piezas));
    }

       public void subtotal() {
        subtotal = v_controller.subtotal(id_venta);
        txtsubtotal.setText(String.valueOf(String.format("%.2f", subtotal)));
    }
        public void importe_total() {
        importe_total = v_controller.seleccionar_importe(id_venta);
        txttotal.setText(String.valueOf(String.format("%.2f", importe_total)));
    }

    public void descuento() {
        descuento = v_controller.descuento(id_venta);
        txtdescuento_total.setText(String.valueOf(String.format("%.2f", descuento)));
        
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtid_cliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtnombre_cliente = new javax.swing.JTextField();
        txt_id_producto = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbproductos = new javax.swing.JTable();
        txtproducto = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtdescuento = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtsubtotal = new javax.swing.JLabel();
        txtdescuento_total = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        txtpiezas = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtno_venta = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtid_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 30, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-búsqueda-40.png"))); // NOI18N
        jButton2.setText("Buscar producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 160, 40));
        getContentPane().add(txtnombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 270, 30));
        getContentPane().add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 30, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("PRODUCTO");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, 30));

        jtbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbproductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 1060, 300));

        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 250, 40));

        txtcantidad.setText("1");
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 120, 30));

        txtdescuento.setText("0");
        getContentPane().add(txtdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 120, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-editar-40.png"))); // NOI18N
        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 160, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-menos-40.png"))); // NOI18N
        jButton4.setText("Eliminar Producto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 160, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-monedas-40.png"))); // NOI18N
        jButton5.setText("Cobrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, 140, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-marca-de-verificación-40.png"))); // NOI18N
        jButton6.setText("Iniciar venta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 140, 40));
        getContentPane().add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, -1, -1));
        getContentPane().add(txtdescuento_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, -1, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, -1, -1));
        getContentPane().add(txtpiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, -1, -1));

        jLabel31.setText("Cantidad");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, -1, -1));

        jLabel30.setText("Descuento %");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, -1, -1));

        jLabel37.setText("SUBTOTAL");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, -1, -1));

        jLabel38.setText("DESCUENTO");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, -1, -1));

        jLabel39.setText("TOTAL A PAGAR");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, -1, -1));

        jLabel40.setText("PIEZAS");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));
        getContentPane().add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setText("VENTA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 50));
        getContentPane().add(txtno_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 20, 10));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/icons8-encuentra-hombre-usuario-40.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        jLabel24.setText("Fecha");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel26.setText("No. de venta");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/inventario.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/sucursales.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/clientes.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/usuarios.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/salir.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel13.setText("PRODUCTOS");

        jLabel15.setText("SUCURSALES");

        jLabel16.setText("CLIENTES");

        jLabel19.setText("USUARIOS");

        jLabel14.setText("INICIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 608, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/joyeria/imagenes/fondo-vistas.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1110, 729));

        jLabel41.setText("PIEZAS");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       //ABRIR LA VISTA DE PRODUCTOS PARA ELEGIR UNO
       
        V_buscarproducto v_buscarproducto = null;
        try {
            v_buscarproducto = new V_buscarproducto(id_venta);
        } catch (SQLException ex) {
            Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        //v_buscarproducto.txtnombre_cliente.setText(txtnombre_cliente.getText());
        v_buscarproducto.setVisible(true);
      
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //if(txtno_venta.getText().equals("")){
            //JOptionPane.showMessageDialog(null, "No se a iniciado la venta");  
        //}else
            //{
            
            
            
                
             
             jLabel23.setVisible(false);
        
             if(txtcantidad.getText().equals("") || txtproducto.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Hay campos vacios");
             }else{
                    int cantidad = Integer.parseInt(txtcantidad.getText());
                    String nombre = "";
                    String descripcion ="";
                    String peso_gramos="";
                    String categoria ="";
                    String precio_gramo="";
                    String precio="";
                    String stock="";
                    ResultSet rs2;
                    
                    try {
                        //OBTENER DATOS DEL PRODUCTO
                        rs2 =dao .datos_producto(Integer.parseInt(txt_id_producto.getText()));
                        while (rs2.next()) {
                            nombre = rs2.getString(1);

                            descripcion = rs2.getString(2);

                            peso_gramos = rs2.getString(3);
                        
                            categoria = rs2.getString(4);
                          
                            precio_gramo = rs2.getString(5); 
                           
                           precio= rs2.getString(6);
                           
                           stock = rs2.getString(7);
                           
                        } 
                       
                          
                        double precio_final;
                        double descuento =(Double.parseDouble(precio)*  Double.parseDouble(txtdescuento.getText())/100);
                        precio_final = (Double.parseDouble(precio)- descuento) * Integer.parseInt(txtcantidad.getText());
                        v_ventaDao.insertarVentaProducto(Integer.parseInt(txt_id_producto.getText()),String.valueOf(cantidad) , String.valueOf(precio), String.valueOf(descuento), String.valueOf(precio_final), Integer.parseInt(txtno_venta.getText()));
                        
                        v_ventaDao.actualizar_stock(Integer.parseInt(txt_id_producto.getText()), Integer.parseInt(stock)-cantidad);
                        contar_piezas();
                        subtotal();
                        descuento();
                        importe_total();
                       v_controller.fillProductos(jtbproductos, id_venta);

                        
                       
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
             }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
      if (seleccion == "") {
            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
             int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
                System.out.println("Opcion: " + confirm);
                if (confirm == 0) {
                   v_controller.eliminar_producto(id_venta,Integer.parseInt(seleccion));
                       //actualizar stock
                        contar_piezas();
                        subtotal();
                        descuento();
                        importe_total();
                 try {
                     v_controller.refillProductos(jtbproductos, id_venta);
                 } catch (SQLException ex) {
                     Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
                 }
                   
                }
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(v_controller.finalizar_venta(Integer.parseInt(txtno_venta.getText()), txtsubtotal.getText(), txttotal.getText(), txtdescuento.getText())){
            JOptionPane.showMessageDialog(null, "Se a finalizado correctamente");
            this.setVisible(false);            
        }
        JasperReport jr;
        try {
            jr = (JasperReport) JRLoader.loadObject(V_Inventario.class.getResource("/Reportes/Ventas.jasper"));
            JasperPrint jp = JasperFillManager.fillReport(jr, null,
       DriverManager.getConnection("jdbc:mysql://localhost:3306/bdjoyeria","root",""));
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (JRException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(V_Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //CUANDO EL CLIENTE ES PUBLICO EN GENERAL EL ID ES 1
        if(txtnombre_cliente.getText().equals("")){
             int confirm = JOptionPane.showConfirmDialog(null, "¿El cliente es publico en general?", "CLiente", JOptionPane.YES_NO_OPTION);
        System.out.print("Opción: " + confirm);
        if (confirm == 0) {
             JOptionPane.showMessageDialog(null, v_controller.iniciar_venta(2,1 ,5));
                 try {
                     id_venta= v_controller.seleccionar_idVenta();
                     System.err.println(id_venta);
                     datos_Venta();
                 } catch (SQLException ex) {
                     Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
                 }
             
             
        }else{
            //AQUI SE ELIGE EL CLIENTE
            JOptionPane.showMessageDialog(null, "es necesario seleccionar un cliente");
        }
        }else{
              JOptionPane.showMessageDialog(null, v_controller.iniciar_venta(Integer.parseInt(txtid_cliente.getText()),1 ,5));
               try {
                     id_venta= v_controller.seleccionar_idVenta();
                      System.err.println(id_venta);
                      datos_Venta();
                 } catch (SQLException ex) {
                     Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
                 }
        }
       
        
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        
        V_buscarcliente buscarCliente = null;
        try {
            buscarCliente = new V_buscarcliente(id_venta);
        } catch (SQLException ex) {
            Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
        buscarCliente.setVisible(true);
        this.setVisible(false);
        
               
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jtbproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbproductosMouseClicked
        // TODO add your handling code here:
    
      
        seleccion= (String) jtbproductos.getValueAt(jtbproductos.getSelectedRow(),0).toString();
        System.err.println(seleccion);
    }//GEN-LAST:event_jtbproductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new V_ventas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(V_ventas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbproductos;
    public static javax.swing.JTextField txt_id_producto;
    public static javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JLabel txtdescuento_total;
    private javax.swing.JLabel txtfecha;
    public static javax.swing.JTextField txtid_cliente;
    private javax.swing.JLabel txtno_venta;
    public static javax.swing.JTextField txtnombre_cliente;
    private javax.swing.JLabel txtpiezas;
    public static javax.swing.JTextField txtproducto;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
